version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data/db/mongodb:/data/db
    networks:
      - taller-network

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    container_name: webserver
    ports:
      - 9505:9000
    volumes:
      - ./webserver:/app/webserver:rw
    depends_on:
      - mongodb
    networks:
      - taller-network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - 7515:5432
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    networks:
      - taller-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - webserver
      - postgres

networks:
  taller-network:
    name: taller-network
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
