version: '3'

services:
  mongodb:
    image: mongo:4.4-focal
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data/container_mongodb:/data/db
    networks:
      - taller-network

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5439:5439
    volumes:
      - ./data/container_postgresql:/var/lib/postgresql/data
    networks:
      - taller-network

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    ports:
      - 9000:9000
    volumes:
      - ./webserver:/app/webserver:rw
    depends_on:
      - mongodb
      - postgres
    networks:
      - taller-network

networks:
  taller-network:
    name: taller-network
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
